# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    - DIST=xenial
    # Make sure beaver is in the PATH
    - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

install: beaver dlang install

jobs:
    include:
        # env:, before_install: and install: are inherited and we don't need to
        # override them.

        - stage: Test
          env:
            matrix:
              - DMD=dmd1 F=production
              - DMD=dmd1 F=devel
              - DMD=dmd-transitional F=production
              - DMD=dmd-transitional F=devel
          script:
              - beaver dlang make
              # Build packages too, this should be done by beaver:
              # https://github.com/sociomantic-tsunami/beaver/issues/34
              - beaver dlang make pkg

        - stage: Upload Package
          if: tag IS present
          env: DMD=dmd1 F=production
          script:
              - beaver dlang make pkg
              - beaver bintray upload -d sociomantic-tsunami/nodes/dhtnode
                build/last/pkg/*.deb
